export const PRODUCTS: Record<string, string> = {
  agl_rewards: "AGL Rewards",
  alinta_energy_rewards: "Alinta Energy Rewards",
  aust_unity_wellplan: "Aust Unity Wellplan",
  budget_direct_rewards: "Budget Direct Rewards",
  bupa_life_rewards: "Bupa Life Rewards",
  cash_rewards: "Cash-rewards",
  entertain_frequent_values: "Entertain./ Frequent Values",
  hcf: "HCF",
  lumo_rewards: "Lumo Rewards",
  macquarie_market_place: "Macquarie Market-place",
  member_advantage: "Member Advantage",
  nib_rewards: "NIB Rewards",
  nrma_benefits: "NRMA Benefits",
  perkbox: "Perkbox",
  racq_lifestyle: "RACQ Lifestyle",
  redeem_your_gift_card: "Redeem Your Gift Card",
  reward_gateway: "Reward Gateway",
  shopback: "ShopBack",
}
