export const GIFT_CARDS: Record<string, string> = {
  seven_eleven_digital: '7-Eleven (Digital)',
  accor_live_limitless: 'Accor Live Limitless',
  adore_beauty: 'Adore Beauty',
  adrenaline: 'Adrenaline',
  airbnb: 'Airbnb',
  amart_furniture: 'Amart Furniture',
  amazon: 'Amazon',
  ampol: 'Ampol',
  anaconda: 'Anaconda',
  angus_coote: 'Angus & Coote',
  apple: 'Apple',
  appliances_online: 'Appliances Online',
  asos: 'asos',
  the_athlete_s_foot: 'The Athlete\'s Foot',
  autobarn: 'Autobarn',
  aveda: 'Aveda',
  store: 'Store',
  barbeques_galore: 'Barbeques Galore',
  bcf: 'BCF',
  beauty_spa_gift_card: 'Beauty & Spa Gift Card',
  best_beauty_wellness_card: 'Best Beauty & Wellness Card',
  best_less: 'Best & Less',
  best_restaurants_card: 'Best Restaurants Card',
  betta_home_living: 'Betta Home Living',
  big_w: 'BIG W',
  binge: 'Binge',
  bing_lee: 'Bing Lee',
  bobbi_brown: 'Bobbi Brown',
  bonds: 'Bonds',
  bonds_kids: 'Bonds Kids',
  boohoo: 'Boohoo',
  booktopia: 'Booktopia',
  boost_juice: 'Boost Juice',
  bottle_o: 'Bottle O',
  boutique_wine_and_champagne: 'Boutique Wine and Champagne',
  bp: 'BP',
  bunnings: 'Bunnings',
  bws: 'BWS',
  the_card_network_the_active_gift_card_retailers: 'The Card Network: The Active Gift Card (retailers)',
  the_card_network_the_baby_gift_card_retailers: 'The Card Network: The Baby Gift Card (retailers)',
  the_card_network_the_cinema_gift_card_retailers: 'The Card Network: The Cinema Gift Card (retailers)',
  the_card_network_the_him_gift_card_retailers: 'The Card Network: The Him Gift Card (retailers)',
  the_card_network_the_her_gift_card_retailers: 'The Card Network: The Her Gift Card (retailers)',
  the_card_network_the_kids_gift_card_retailers: 'The Card Network: The Kids Gift Card (retailers)',
  the_card_network_the_home_gift_card_retailers: 'The Card Network: The Home Gift Card (retailers)',
  the_card_network_the_online_gift_card_retailers: 'The Card Network: The Online Gift Card (retailers)',
  the_card_network_the_pamper_card_retailers: 'The Card Network: The Pamper Card (retailers)',
  the_card_network_the_pub_bar_card_retailers: 'The Card Network: The Pub & Bar Card (retailers)',
  the_card_network_the_restaurant_gift_card_retailers: 'The Card Network: The Restaurant Gift Card (retailers)',
  the_card_network_the_teen_gift_card_retailers: 'The Card Network: The Teen Gift Card (retailers)',
  caf_choice: 'Café Choice',
  catch: 'Catch',
  category_choice_fuel: 'Category Choice Fuel',
  category_choice_groceries: 'Category Choice Groceries',
  category_choice_pets_vets: 'Category Choice Pets & Vets',
  cellarbrations: 'Cellarbrations',
  chemist_warehouse: 'Chemist Warehouse',
  city_beach: 'City Beach',
  classbento: 'ClassBento',
  clinique: 'Clinique',
  coles: 'Coles',
  collins_booksellers: 'Collins Booksellers',
  cotton_on: 'Cotton On',
  cotton_on_body: 'Cotton On Body',
  cotton_on_kids: 'Cotton On Kids',
  country_road: 'Country Road',
  dan_murphy_s: 'Dan Murphy\'s',
  doordash: 'DoorDash',
  dotti: 'Dotti',
  dr_martens: 'Dr. Martens',
  drummond_golf: 'Drummond Golf',
  dusk: 'Dusk',
  dymocks: 'Dymocks',
  ebay: 'eBay',
  eb_games: 'EB Games',
  eg: 'EG',
  endota: 'Endota',
  entertainment_group_the_gift_of_fun: 'Entertainment Group (The Gift of Fun)',
  est_e_lauder: 'Estée Lauder',
  everyday_wish: 'Everyday WISH',
  event_cinemas: 'Event Cinemas',
  everyplate: 'EveryPlate',
  factorie: 'Factorie',
  first_choice_liquor: 'First Choice Liquor',
  flight_centre: 'Flight Centre',
  foot_locker: 'Foot Locker',
  forever_new: 'Forever New',
  freedom: 'Freedom',
  fresh_beauty_co: 'Fresh Beauty Co.',
  general_pants_co: 'General Pants Co.',
  gift_to_dine: 'Gift To Dine',
  glassons: 'Glassons',
  global_experiences_card: 'Global Experiences Card',
  global_hotel_card: 'Global Hotel Card',
  gocatch: 'GoCatch',
  goldmark: 'Goldmark',
  good_food: 'Good Food',
  the_good_guys: 'The Good Guys',
  google_play: 'Google Play',
  gourmet_traveller: 'Gourmet Traveller',
  h_m: 'H&M',
  hallenstein_brothers: 'Hallenstein Brothers',
  harris_farm_markets: 'Harris Farm Markets',
  harris_scarfe: 'Harris Scarfe',
  harvey_norman: 'Harvey Norman',
  hello_fresh: 'Hello Fresh',
  hey_you: 'Hey You',
  the_holiday_hotel_card: 'The Holiday & Hotel Card',
  home_hardware: 'Home Hardware',
  hotels_com: 'Hotels.com',
  hoyts: 'Hoyts',
  hubbl: 'Hubbl',
  hype_dc: 'Hype DC',
  the_iconic: 'THE ICONIC',
  iga: 'IGA',
  ikea: 'IKEA',
  imvu: 'IMVU',
  intersport: 'INTERSPORT',
  isubscribe: 'isubscribe',
  jag: 'JAG',
  jay_jays: 'Jay Jays',
  jb_hi_fi: 'JB Hi-Fi',
  jo_malone_london: 'Jo Malone London',
  just_jeans: 'Just Jeans',
  kathmandu: 'Kathmandu',
  kayo_sports: 'Kayo Sports',
  kiddo: 'Kiddo',
  kikki_k: 'kikki.K',
  kmart: 'Kmart',
  kobo: 'Kobo',
  kogan: 'Kogan',
  la_mer: 'La Mer',
  laubman_pank: 'Laubman & Pank',
  lego: 'LEGO',
  liquorland: 'Liquorland',
  lorna_jane: 'Lorna Jane',
  luxury_escapes: 'Luxury Escapes',
  m_a_c_cosmetics: 'M.A.C Cosmetics',
  m_a_c_by_myer: 'M.A.C by Myer',
  macpac: 'Macpac',
  me_coffee_merchants: 'ME Coffee Merchants',
  the_meat_wine_co: 'The Meat & Wine Co',
  merivale: 'Merivale',
  michael_hill: 'Michael Hill',
  mimco: 'Mimco',
  mitre_10: 'Mitre 10',
  myer: 'Myer',
  nexon_game_card: 'Nexon Game Card',
  nine_west: 'Nine West',
  oakley: 'Oakley',
  officeworks: 'Officeworks',
  opsm: 'OPSM',
  original_mattress_factory: 'Original Mattress Factory',
  ozsale: 'OZSALE',
  pandora: 'Pandora',
  peter_alexander: 'Peter Alexander',
  playstation_store: 'PlayStation Store',
  platypus: 'Platypus',
  portmans: 'Portmans',
  porters_liquor: 'Porters Liquor',
  priceline: 'Priceline',
  prouds_the_jewellers: 'Prouds the Jewellers',
  purebaby: 'Purebaby',
  rebel: 'rebel',
  redballoon: 'RedBalloon',
  rentalcars_com: 'RentalCars.com',
  restaurant_choice: 'Restaurant Choice',
  riot_games: 'Riot Games',
  rip_curl: 'Rip Curl',
  roblox: 'Roblox',
  rubi_shoes: 'Rubi Shoes',
  saba: 'SABA',
  san_churro: 'San Churro',
  seed_heritage: 'Seed Heritage',
  sephora: 'Sephora',
  shell_viva_energy: 'Shell (Viva Energy)',
  sheridan: 'Sheridan',
  skechers: 'Skechers',
  smiggle: 'Smiggle',
  spa_wellness: 'Spa & Wellness',
  spark_pop: 'Spark Pop',
  sportsgirl: 'Sportsgirl',
  spotify: 'Spotify',
  spotlight: 'Spotlight',
  strandbags_strand: 'Strandbags (Strand)',
  stylerunner: 'Stylerunner',
  sunglass_hut: 'Sunglass Hut',
  supercheap_auto: 'Supercheap Auto',
  supre: 'Supré',
  the_super_retail_group: 'The Super Retail Group',
  swap_adventure_leisure_giftcard_retailers: 'Swap Adventure & Leisure Giftcard (retailers)',
  swap_celebration_giftcard_retailers: 'Swap Celebration Giftcard (retailers)',
  swap_ent_giftcard_retailers: 'Swap Ent. Giftcard (retailers)',
  target: 'Target',
  temple_webster: 'Temple & Webster',
  ticketek: 'Ticketek',
  ticketmaster: 'Ticketmaster',
  toni_guy: 'TONI&GUY',
  total_tools: 'Total Tools',
  travel_associates: 'Travel Associates',
  trenery: 'Trenery',
  tripgift: 'TripGift',
  tripgift_rentacar: 'TripGift – Rentacar',
  twitch: 'Twitch',
  uber: 'Uber',
  uber_eats: 'Uber Eats',
  ultimate_active_wellness: 'Ultimate Active & Wellness',
  ultimate_baby_mum: 'Ultimate Baby & Mum',
  ultimate_beauty_spa: 'Ultimate Beauty & Spa',
  ultimate_birthday: 'Ultimate Birthday',
  ultimate_celebrate: 'Ultimate Celebrate',
  ultimate_eats: 'Ultimate Eats',
  ultimate_everyone: 'Ultimate Everyone',
  ultimate_gaming_bites: 'Ultimate Gaming & Bites',
  ultimate_her: 'Ultimate Her',
  ultimate_him: 'Ultimate Him',
  ultimate_home: 'Ultimate Home',
  ultimate_just_for_you: 'Ultimate Just For You',
  ultimate_kids: 'Ultimate Kids',
  ultimate_students: 'Ultimate Students',
  ultimate_style_shopping: 'Ultimate Style/Shopping',
  ultimate_teens: 'Ultimate Teens',
  ultimate_thank_you: 'Ultimate Thank You',
  ultimate_thanks: 'Ultimate Thanks',
  unison: 'Unison (previously French Connection)',
  united_petroleum: 'United Petroleum',
  village_cinemas: 'Village Cinemas',
  vintage_cellars: 'Vintage Cellars',
  weber_bbq: 'Weber BBQ',
  webjet: 'Webjet',
  witchery: 'Witchery',
  woolworths: 'Woolworths',
  xbox_currency: 'Xbox Currency',
  xbox_game_pass: 'Xbox Game Pass',
  youfoodz: 'Youfoodz'
}
